#MAKEFILE

all: generator merge quick insertion

generator: generator.cpp
	g++ -O3 -o generator generator.cpp

merge: merge.cpp
	g++ -O3 -o merge merge.cpp

quick: quick.cpp
	g++ -O3 -o quick quick.cpp

insertion: insertion.cpp
	g++ -O3 -o insertion insertion.cpp

clean:
	rm generator merge quick insertion
